language: python
python: 2.7
os:
    - linux
    - osx
sudo: false
cache:
    - pip
    - apt

env:
    - TOX_ENV=py27
    - TOX_ENV=py34
    - TOX_ENV=pypy
    - TOX_ENV=pyflakes
    - TOX_ENV=manifest

matrix:
  fast_finish: true
  allow_failures:
    - os: osx
    - env: TOX_ENV=pypy
    - env: TOX_ENV=py34
    - env: TOX_ENV=pyflakes
    - env: TOX_ENV=manifest

addons:
  apt:
    sources:
    - kalakris-cmake
    - ubuntu-toolchain-r-test

addons:
  apt:
    packages:
    - cmake
    - build-essential
    - libgdal-dev
    - libhdf5-serial-dev

install:
  - echo "libgdal version `gdal-config --version`"
  - echo "GCC version `gcc --version`"
  - pip install pip --upgrade
  - pip install tox coveralls
  - git clone https://github.com/Mindwerks/worldengine-data.git ../worldengine-data

# # command to run tests
script:
  - tox -e $TOX_ENV

notifications:
    email: false

after_success:
    - coveralls